### ISSUE TITLE
Don't use hardcoded watson credentials

### ISSUE THREAD

**Issue by stevemar** [ragudiko/wks-nlu-sms-analysis#1]
You'll need an environment or config file to store the Discovery credentials, they are currently hard-coded (https://github.com/ragudiko/wks-nlu-sms-analysis/blob/master/src/main/java/com/ibm/watson/nlu/SimpleNLUClient.java#L80)

**Comment by ragudiko** [comment]
Will be done. We are using env option.

**Comment by ragudiko** [comment]
Fixed, using env variables.

**Comment by ragudiko** [comment]
Steve, this should be closed as we are using env variable to hold credentials.
