### ISSUE TITLE
Steps for training and evaluating

### ISSUE THREAD

**Issue by rhagarty** [ragudiko/wks-nlu-sms-analysis#13]
Looking at the latest version of the README:

For step "8. Create the model", I'm not sure what steps to take here. I added instructions for the way I proceeded, but at the end my performance results look different than the screen shot. I selected "All" and hit "Train & Evaluate".

**Comment by ragudiko** [comment]
I have modified steps and screenshots to fix this issue. In practice we have to consider 1000 messages. Also we have to separate training and evaluation sets.
