### ISSUE TITLE
Deploying the model to NLU

### ISSUE THREAD

**Issue by rhagarty** [ragudiko/wks-nlu-sms-analysis#14]
Need some clarification here. How did you get the additional versions of the model show in the screen shots? And what action do you take to start the deploy process?

**Comment by ragudiko** [comment]
Any time you evaluate with different annotation set, you get new F1/precison/recall value. You expect F1 value to be around .6 for decent model performance(To get such performance you need thousands of messages). Once you are happy with performance of model, you can take snapshot. When you take snapshot, a new version is created. 
**Note**: For demo purpose I evaluate taking 3 messages to get better F1 value(this is just a hack). Usually training set and evaluation set will be separate, they are not mixed to avoid bias. But to do so we need thousands of sms messages as mentioned earlier.

**Comment by markstur** [comment]
Starting w/ a hardcoded modelId seems like a bad idea.

**Comment by ragudiko** [comment]
Mark, developer has to note the model id post their deployment(step 9). The Rich has covered configuration of model id as part of "Add NLU Credentials and WKS Model ID to config.properties file" section in README. As you mentioned in other issue, WATSON_KNOWLEDGE_STUDIO_MODEL_ID property will be placeholder for model id.

**Comment by rhagarty** [comment]
New screen shots and README accurately describe this process now.
