### ISSUE TITLE
File purpose and uploaded docs to WKS

### ISSUE THREAD

**Issue by rhagarty** [ragudiko/wks-nlu-sms-analysis#17]
What is data/offers_msg.xls used for? 

Is it related to the importing of document sets?
If so, doesn't it need to be in csv format?

Also, when we upload the corpus documents, we state that it isn't necessary, but recommended for beginners. What is the alternative?

**Comment by ragudiko** [comment]
Removed unwanted file as we do not need it for current implementation approach. 

corpus documents: Alternative approach is to upload new files(txt format as specified by wks) and follow other steps. The difference is when you start human annotation, you will not find any annotated data. i.e. You start annotation from scratch. In our approach we are using corpus documents which has annotated(meta) data, so when we start annotation, we find the documents are annotated.

**Comment by rhagarty** [comment]
Please use PR's for fixes so we can easily see the changes.

**Comment by stevemar** [comment]
++ please use PRs so we can track things more easily.

**Comment by stevemar** [comment]
and we're more aware of the changes

**Comment by ragudiko** [comment]
Fine Steve/Rich, will take care of it.
