### ISSUE TITLE
Deploy to IBM Cloud not working

### ISSUE THREAD

**Issue by rhagarty** [ragudiko/wks-nlu-sms-analysis#18]
I can run the app, but SMS messages are not processed.

**Comment by ragudiko** [comment]
model id changed as i have to delete multiple version and have single version for screenshot. The current model id is **10:047ef383-83e6-4e90-913b-af04b731859d**. Sorry about that.

**Comment by markstur** [comment]
that modelId does not work either  :(

**Comment by ragudiko** [comment]
10:047ef383-83e6-4e90-913b-af04b731859d: This model id is still valid. I verified our deployed application in below link.
https://wks-nlu-sms-analysis-concerned-datcha.mybluemix.net/

**Comment by markstur** [comment]
I think this is resolved w/ error handling and the MODEL_ID = placeholder plus README steps.
Not sure if that is completely resolved.

**Comment by ragudiko** [comment]
Mark, I had discussion with Rich on this. There is no automatic deployment of model to NLU. It is very much manual process. The Rich has covered configuration of model id as part of "Add NLU Credentials and WKS Model ID to config.properties file" section in README.

**Comment by rhagarty** [comment]
This works now and is described in README. This will be a totally manual process where user generates their own model ID to use with the app.
