### ISSUE TITLE
Create a simple webapp frontend 

### ISSUE THREAD

**Issue by stevemar** [ragudiko/wks-nlu-sms-analysis#2]
It would be great to provide a very simple front-end to be able to select a message to analyze, and show the output. (https://github.com/ragudiko/wks-nlu-sms-analysis/blob/master/src/main/java/com/ibm/watson/nlu/SimpleNLUClient.java#L81)

**Comment by ragudiko** [comment]
Will be done. We are providing two ways to feed sms for analysis.  One text area where user can enter/paste the sms text. The other option is to browse sms text file from drive.

**Comment by ragudiko** [comment]
Done. We are providing UI to enter sms text.

**Comment by stevemar** [comment]
this is done, closing.
