### ISSUE TITLE
Where's the how-to build the war?

### ISSUE THREAD

**Issue by markstur** [ragudiko/wks-nlu-sms-analysis#28]
there's a pom.xml and a build.xml -- step by step readme should mention how to build this thing

**Comment by stevemar** [comment]
@markstur is this good enough: https://github.com/IBM/sms-analysis-with-wks#build-and-run

Or are you looking for output too?

**Comment by markstur** [comment]
removed the ant build.xml.  Made maven build the .war.  Documented in the README.

Closed with #29
