### ISSUE TITLE
Check in JSON files for SMS's

### ISSUE THREAD

**Issue by stevemar** [ragudiko/wks-nlu-sms-analysis#5]
Either replace the CSV or also check in JSON (or HTML) files into the repository. If our expectation is that folks use Discovery, they can't drop in CSV files.

**Comment by ragudiko** [comment]
We are using NLU and wks not discovery. The sms is fed as text or via file upload which will then processed by NLU service.

**Comment by stevemar** [comment]
we're using csv files and corpus files. closing.

**Comment by ragudiko** [comment]
Steve, small correction. I will be sharing folders having sms in the form of text files. These files are used in wks. Instead of updating csv file with additional 80 sms, I prefer to dump all 120 sms text files. I have discussed with Rich on this. Sorry for the confusion.
