### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by sophierm** [ragudiko/wks-nlu-sms-analysis#51]
The website has problems showing German umlauts (ä, ö, ü) even though utf-8 charset is activated... any idea, why?
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/30292726/41717284-8828d2aa-7559-11e8-949a-caa53dd16e74.png">

**Comment by stevemar** [comment]
@ragudiko @rameshpoomalai can you look at this issue?

**Comment by rameshpoomalai** [comment]
Hi @stevemart, We will look into it.

**Comment by rameshpoomalai** [comment]
Hi @stevemart ,

Please review and approve the pull request for this issue.
