### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by rhagarty** [ragudiko/wks-nlu-sms-analysis#7]
@ragudiko 

I deployed to IBM Cloud and see both the App and NLU service created successfully.

I tired both 'curl' commands, but only the first one worked. The second returned:
{
   "Language": "en",
   "error": "model not found",
   "code": 404
}

I then ran the app, and entered text. The Watson spinner came on for awhile and then went away. Nothing else was displayed. 
I looked in the logs and found numerous errors basically around 'model not found'.

If there is more setup that is required, it needs to be added to the README.

**Comment by ragudiko** [comment]
Hi Rich,
The wks model has to be created. There is no way to automate creating/deploying wks model to nlu. It is a manual process and Readme file has steps(screenshots) of deployment of wks model to nlu. As you said, I will give more detailed steps right from creating project in wks to deploying of the model to nlu.

**Comment by rhagarty** [comment]
@ragudiko 
ok - will wait for those instructions. And don't worry so much about format right now, just getting these steps added to the README is most important.

**Comment by ragudiko** [comment]
HI Rich,
I have uploaded latest Readme file with all steps required.
The wks was moved from market place to ibm cloud, so my wks model ID was not found when you tried. The model is 10:a5172791-b31b-4b0d-b546-3610ec652ca4. I have updated the same in Read me file.

**Comment by rhagarty** [comment]
@ragudiko - thanks for the update. We can probably reduce the number of screen shots by consolidating some actions and by adding some textual descriptions for some of the steps, but this is a good start. 

I went through the manual setup and have some questions (sorry, I'm new to WKS).

1) You state that you can skip step "5. Upload Document".  What is the purpose of the screen shots? Looks like an important step.
2) in step "6. Import Corpus Documents". How did the documents in the screen shot get there? Am I supposed to "Upload document sets" and pick the corpus zip file? I did that and the dialog asked if I wanted to "upload the original workspace's type system first". Should I? I took the default which is "yes".
3) Also in step "6. Import Corpus Documents", each of the screen shots is showing a different set of documents. Can you clarify?
4) I'm stuck at step "7. Create Annotation Set". I don't see the base set "FirstSmsSet.txt_set". I assume I didn't upload the correct document sets.

**Comment by ragudiko** [comment]
Hi Rich,
By mistake i wrote changes done by steve/you. Later corrected things and pushed to repository.
Point 1 and 2: For beginners import **corpus** documents is good so i just kept that step and omitted upload document.
Point 3: Based on first step this confusion should be removed?
Point 4: This is a good catch. This was based on you upload documents we try to rename document set to FirstSmsSet.txt_set. This is not required now and I have done changes to the screenshots to follow the steps based on import corpus documents. I removed those screenshots of renaming documents. Also I had do relevant change to model_training_and_evaluation-2.png screenshot to make sure FirstSmsSet.txt_set is not seen.
I will look into reducing screenshots. Definitely we can omit few screens in upload/task/model training steps. Hope this should be fine.
Thanks a lot for feedback.
